apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

configMapGenerator:
  - name: landingpage-content
    files:
      - site/index.html
      - site/style.css

generatorOptions:
  disableNameSuffixHash: true
